transactions_payload = {
  "fire_webhooks": True,
  "group_title": "Hardware & DIY",
  "transactions": [
    {
      "type": "withdrawal",
      "amount": "89.95",
      "date": "2020-08-25",
      "description": "BORR SDS-P 10X310MM",
      "currency_id": "10",
      "currency_code": "SEK",
      "source_name": "Extra",
      "destination_name": "BAUHAUS",
      "tags": "Firefly Assistant",
      "notes": ""
    },
    {
      "type": "withdrawal",
      "amount": "453.25",
      "date": "2020-08-25",
      "description": "KABEL UTP CAT 5E",
      "currency_id": "10",
      "currency_code": "SEK",
      "source_name": "Extra",
      "destination_name": "BAUHAUS",
      "tags": "Firefly Assistant",
      "notes": ""
    }
  ]
}


transactions_response = {
  "data": {
    "type": "transactions",
    "id": "94",
    "attributes": {
      "created_at": "2025-09-06T21:51:52+02:00",
      "updated_at": "2025-09-06T21:51:52+02:00",
      "user": "1",
      "user_group": "1",
      "group_title": "Hardware & DIY",
      "transactions": [
        {
          "user": "1",
          "transaction_journal_id": "358",
          "type": "withdrawal",
          "date": "2020-08-25T00:00:00+02:00",
          "order": 0,
          "object_has_currency_setting": True,
          "currency_id": "10",
          "currency_code": "SEK",
          "currency_name": "Svensk krona",
          "currency_symbol": "kr.",
          "currency_decimal_places": 2,
          "foreign_currency_id": None,
          "foreign_currency_code": None,
          "foreign_currency_name": None,
          "foreign_currency_symbol": None,
          "foreign_currency_decimal_places": 0,
          "primary_currency_id": "10",
          "primary_currency_code": "SEK",
          "primary_currency_name": "Svensk krona",
          "primary_currency_symbol": "kr.",
          "primary_currency_decimal_places": 2,
          "amount": "453.250000000000",
          "pc_amount": "453.250000000000",
          "foreign_amount": None,
          "pc_foreign_amount": None,
          "source_balance_after": None,
          "pc_source_balance_after": None,
          "destination_balance_after": None,
          "pc_destination_balance_after": None,
          "source_balance_dirty": True,
          "destination_balance_dirty": True,
          "description": "KABEL UTP CAT 5E",
          "source_id": "12",
          "source_name": "Extra",
          "source_iban": "",
          "source_type": "Asset account",
          "destination_id": "67",
          "destination_name": "BAUHAUS",
          "destination_iban": None,
          "destination_type": "Expense account",
          "budget_id": None,
          "budget_name": None,
          "category_id": None,
          "category_name": None,
          "bill_id": None,
          "bill_name": None,
          "subscription_id": None,
          "subscription_name": None,
          "reconciled": False,
          "notes": None,
          "tags": [
            "Firefly Assistant"
          ],
          "internal_reference": None,
          "external_id": None,
          "original_source": "ff3-v6.3.2",
          "recurrence_id": None,
          "recurrence_total": None,
          "recurrence_count": None,
          "external_url": None,
          "import_hash_v2": "d546a5692732a4604d75a34281a78bc840ac0be6d25c34003020d18954e24068",
          "sepa_cc": None,
          "sepa_ct_op": None,
          "sepa_ct_id": None,
          "sepa_db": None,
          "sepa_country": None,
          "sepa_ep": None,
          "sepa_ci": None,
          "sepa_batch_id": None,
          "interest_date": None,
          "book_date": None,
          "process_date": None,
          "due_date": None,
          "payment_date": None,
          "invoice_date": None,
          "longitude": None,
          "latitude": None,
          "zoom_level": None,
          "has_attachments": False
        },
        {
          "user": "1",
          "transaction_journal_id": "357",
          "type": "withdrawal",
          "date": "2020-08-25T00:00:00+02:00",
          "order": 0,
          "object_has_currency_setting": True,
          "currency_id": "10",
          "currency_code": "SEK",
          "currency_name": "Svensk krona",
          "currency_symbol": "kr.",
          "currency_decimal_places": 2,
          "foreign_currency_id": None,
          "foreign_currency_code": None,
          "foreign_currency_name": None,
          "foreign_currency_symbol": None,
          "foreign_currency_decimal_places": 0,
          "primary_currency_id": "10",
          "primary_currency_code": "SEK",
          "primary_currency_name": "Svensk krona",
          "primary_currency_symbol": "kr.",
          "primary_currency_decimal_places": 2,
          "amount": "89.950000000000",
          "pc_amount": "89.950000000000",
          "foreign_amount": None,
          "pc_foreign_amount": None,
          "source_balance_after": None,
          "pc_source_balance_after": None,
          "destination_balance_after": None,
          "pc_destination_balance_after": None,
          "source_balance_dirty": True,
          "destination_balance_dirty": True,
          "description": "BORR SDS-P 10X310MM",
          "source_id": "12",
          "source_name": "Extra",
          "source_iban": "",
          "source_type": "Asset account",
          "destination_id": "67",
          "destination_name": "BAUHAUS",
          "destination_iban": None,
          "destination_type": "Expense account",
          "budget_id": None,
          "budget_name": None,
          "category_id": None,
          "category_name": None,
          "bill_id": None,
          "bill_name": None,
          "subscription_id": None,
          "subscription_name": None,
          "reconciled": False,
          "notes": None,
          "tags": [
            "Firefly Assistant"
          ],
          "internal_reference": None,
          "external_id": None,
          "original_source": "ff3-v6.3.2",
          "recurrence_id": None,
          "recurrence_total": None,
          "recurrence_count": None,
          "external_url": None,
          "import_hash_v2": "72687961443a6067d2a9dc32f082706036c20969c86d359a188a76cb1040b3b2",
          "sepa_cc": None,
          "sepa_ct_op": None,
          "sepa_ct_id": None,
          "sepa_db": None,
          "sepa_country": None,
          "sepa_ep": None,
          "sepa_ci": None,
          "sepa_batch_id": None,
          "interest_date": None,
          "book_date": None,
          "process_date": None,
          "due_date": None,
          "payment_date": None,
          "invoice_date": None,
          "longitude": None,
          "latitude": None,
          "zoom_level": None,
          "has_attachments": False
        }
      ]
    },
    "links": {
      "self": "https://budget.itkon.se/api/v1/transactions/94",
      "0": {
        "rel": "self",
        "uri": "/transactions/94"
      }
    }
  }
}